### ISSUE TITLE
"Please go to home.mycroft.ai to register"

### ISSUE THREAD

**Issue by singpolyma** [ethanaward/pianobar-skill#11]
This is what my Mark 1 says to me today.  It was working fine before (well "fine" if you discount the constant freezes because pianobar/libao hates Pulseaudio :P) but I upgraded today and now I get this.  Maybe the settings API has changed slightly in the latest mycroft core?

I checked, and my `settings.json` is still in place with email and password.

**Comment by LearnedVector** [comment]
Hello singpolyma, are you still experiencing this problem?

**Comment by LearnedVector** [comment]
It should be solved now with the new update.

**Comment by singpolyma** [comment]
working for me now, thanks!
