### ISSUE TITLE
Auto-resume on false positive or after intervening unrelated command

### ISSUE THREAD

**Issue by skeledrew** [ethanaward/pianobar-skill#12]
Resume playback when recognition is falsely triggered (if no command given). Currently has to be resumed by user. Also ensure song title display is restored on resume.

**Comment by LearnedVector** [comment]
@skeledrew the implementation for that is a hack right now. The new audio service should be able to handle that if turned on. https://github.com/MycroftAI/mycroft-core/wiki/Audio-Service#pulse-audio-features

**Comment by skeledrew** [comment]
@Mn0491 another quick hack shouldn't be much IMO. Just do something similar to skill-date-time with he timer and have it resume playing if there's nothing else active or the time is being displayed (may need to make other exceptions also).

**Comment by LearnedVector** [comment]
@skeledrew makes sense. But the new audio service actually solves the problem of resuming playback right out of the box. what we could do is take out the recognizer loops, and just use the built in audio service to resume playback, then add a way to ensure song title display is restored

**Comment by LearnedVector** [comment]
fixed, using the mycroft-audio service. Look at README for more details
